import { lazy, Suspense, useCallback, useEffect, useRef, useState } from 'react';
import { ArrowDownToLine, ArrowLeftRight, ArrowRight, Check, ChevronRight, CircleDashed, FileClock, Fingerprint, GitBranch, Layers3, Link2, LockKeyhole, LogOut, RefreshCw, ShieldCheck, Upload } from 'lucide-react';
import { api, ApiError, errorMessage, type AuditEvent, type ChainState, type Integrations, type Reconciliation, type Session, type Trade, type WorldStatus } from './api';
import { Button, Empty, Hash, Notice } from './components/ui';
import { Evidence } from './components/Evidence';
import { Proposal } from './components/Proposal';
import { AgentReview } from './components/AgentReview';
import { Brand } from './components/Brand';
import { Welcome } from './components/Welcome';
import { ChainSettlement } from './components/ChainSettlement';
import { amount, dateTime } from './format';

const WorldVerification = lazy(() => import('./components/WorldVerification'));
type View = 'review' | 'agreement' | 'audit' | 'connections';
const noWorld: WorldStatus = { configured: false, approvals_ready: false, trust: null, environment: null };
// Who the visitor is acting as. The hosted demo signs everyone in as the buyer's scoped agent.
function identity(session: Session) {
  const p = session.principal!;
  const role = `${p.side === 'buyer' ? 'Buyer' : 'Broker'} ${p.kind === 'agent' ? 'agent' : 'approver'}`;
  return { initials: p.side === 'buyer' ? 'BU' : 'BR', role, where: session.hosted ? 'Hosted synthetic demo' : session.demo ? 'Local synthetic sample' : p.id };
}
const nav = [{ id: 'review', label: 'Trade review', Icon: ArrowLeftRight }, { id: 'agreement', label: 'Agreement', Icon: ShieldCheck }, { id: 'audit', label: 'Audit trail', Icon: FileClock }, { id: 'connections', label: 'Connections', Icon: Link2 }] as const;
export function App() {
  const [session, setSession] = useState<Session | null>(null); const [loading, setLoading] = useState(true);
  const [view, setView] = useState<View>('review'); const [trade, setTrade] = useState<Trade | null>(null);
  const [reconciliation, setReconciliation] = useState<Reconciliation | null>(null); const [audit, setAudit] = useState<AuditEvent[]>([]);
  const [world, setWorld] = useState<WorldStatus>(noWorld); const [modelConfigured, setModelConfigured] = useState(false);
  const [chain, setChain] = useState<ChainState | null>(null); const [suiPackage, setSuiPackage] = useState<string | null>(null);
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const generation = useRef(0);
  const tradeId = session?.principal?.tradeIds[0] ?? 'TB-001';
  const refresh = useCallback(async () => {
    const current = ++generation.current; setError('');
    try {
      const [nextTrade, nextReconciliation, nextAudit, integrations] = await Promise.all([
        api<Trade>(`/trades/${tradeId}`), api<Reconciliation>(`/trades/${tradeId}/reconciliation`), api<{ events: AuditEvent[] }>(`/trades/${tradeId}/audit`), api<Integrations>('/integrations'),
      ]);
      if (current !== generation.current) return;
      setTrade(nextTrade); setReconciliation(nextReconciliation); setAudit(nextAudit.events); setWorld(integrations.world_id); setModelConfigured(integrations.agents.configured); setSuiPackage(integrations.sui.deployed ? integrations.sui.package_id : null);
      // Chain state reads the escrow from Sui; an RPC hiccup must not hide the evidence.
      if (integrations.sui.deployed) api<ChainState>(`/trades/${tradeId}/chain`, { timeout: 20_000 }).then(next => { if (current === generation.current) setChain(next); }).catch(e => { if (current === generation.current) setError(`Sui state unavailable: ${errorMessage(e)}`); });
    } catch (error) {
      if (current !== generation.current) return;
      if (error instanceof ApiError && error.status === 404) { setTrade(null); setReconciliation(null); }
      else if (error instanceof ApiError && error.status === 401) { setSession(previous => ({ principal: null, demo_available: true, hosted: previous?.hosted })); setTrade(null); setError('Your session ended. Sign in again to continue.'); }
      else setError(errorMessage(error));
    }
  }, [tradeId]);
  useEffect(() => { const controller = new AbortController(); api<Session>('/session', { signal: controller.signal }).then(setSession).catch(e => { if (!controller.signal.aborted) setError(errorMessage(e)); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, []);
  useEffect(() => { if (session?.principal) void refresh(); }, [session, refresh]);
  useEffect(() => { document.title = `TradeBridge | ${nav.find(n => n.id === view)!.label}`; }, [view]);
  const latest = trade?.candidates.at(-1);
  const approvalsDone = ['buyer', 'broker'].every(side => ['HUMAN_APPROVED', 'CONSUMED'].includes(reconciliation?.approvals[side] ?? ''));
  const settled = Boolean(chain?.settlement?.verified);
  const attested = Boolean(chain?.steps.some(step => step.key === 'attest' && step.success));
  return <div className={`app-shell ${session?.principal ? '' : 'entry-shell'}`}><a className="skip-link" href="#main">Skip to content</a>
    <aside className="sidebar"><a className="brand" href="#main" onClick={() => setView('review')}><Brand /></a><p className="sidebar-label">WORKSPACE</p><nav aria-label="Workspace">{nav.map(({ id, label, Icon }) => <button key={id} aria-label={label} onClick={() => setView(id)} aria-current={view === id ? 'page' : undefined}><Icon size={18} />{label}{id === 'review' && trade && <span className="nav-count">1</span>}</button>)}</nav><section className="sidebar-note"><LockKeyhole size={19} /><strong>Agreement before execution.</strong><p>Every correction needs two verified human approvals.</p></section>{session?.principal && <footer className="sidebar-footer"><span className="avatar" aria-hidden="true">{identity(session).initials}</span><span>Signed in as {identity(session).role.toLowerCase()}<small>{identity(session).where}</small></span></footer>}</aside>
    <div className="workspace"><header className="topbar">{!session?.principal ? <><a className="brand" href="#main"><Brand /></a><nav className="entry-nav" aria-label="Introduction"><a href="#review-method">How it works</a>{!session?.hosted && <a href="#access">Workspace access <ArrowRight size={15} /></a>}</nav></> : <><span>Workspace <ChevronRight size={14} />{nav.find(n => n.id === view)!.label}</span><div><span className={`network ${suiPackage ? 'live' : ''}`}><span />{session?.hosted ? 'Hosted demo' : suiPackage ? 'Sui Testnet' : 'Local environment'}</span>{session?.principal && <Button kind="ghost" onClick={async () => { try { await api('/session', { method: 'DELETE' }); generation.current++; setSession(previous => ({ principal: null, demo_available: true, hosted: previous?.hosted })); setTrade(null); setReconciliation(null); setAudit([]); } catch (e) { setError(errorMessage(e)); } }} aria-label={session.demo ? 'Leave demo and remove its working data' : 'Sign out'}><LogOut size={17} /><span className="hide-small">{session.demo ? 'Leave demo' : 'Sign out'}</span></Button>}</div></>}</header>
      <main id="main" tabIndex={-1}>
        {error && <Notice error>{error} <Button kind="ghost" onClick={() => session?.principal ? void refresh() : void api<Session>('/session').then(setSession).catch(e => setError(errorMessage(e)))}>Retry</Button></Notice>}
        {loading ? <Empty title="Opening your workspace">Checking your session…</Empty> : !session?.principal ? <Welcome onSession={setSession} demoAvailable={session?.demo_available ?? true} hosted={session?.hosted} /> : <>
          <header className="page-heading"><div><p className="breadcrumb">Bilateral reconciliation / {tradeId}</p><h1>{view === 'review' ? 'Trade review' : nav.find(n => n.id === view)!.label}</h1><p>{view === 'review' ? 'Resolve the difference. Keep the evidence.' : view === 'audit' ? 'An ordered record of every saved change.' : view === 'agreement' ? 'The exact terms both parties must authorize.' : 'Integration readiness and the remaining trust boundaries.'}</p></div><div className="heading-actions">{session.demo && <span className="sample-label">Synthetic demo</span>}<Button busy={busy} onClick={async () => { setBusy(true); await refresh(); setBusy(false); }}><RefreshCw size={16} />Refresh</Button></div></header>
          <section hidden={view !== 'review'}>
            {session.hosted ? <Notice>Synthetic demo · you act as the buyer’s scoped agent: you can compare records and propose terms, but not verify, approve or settle. This session lasts one hour, and leaving the demo removes its saved workspace. Use sample information only.</Notice> : <ImportSource tradeId={tradeId} revision={trade?.revision ?? 0} side={session.principal.side} onSaved={refresh} />}
            {!trade || !reconciliation ? <Empty title="Start with the source records">Import the buyer and broker CSVs using their separate development accounts. Original records are preserved.</Empty> : <>
              <section className="trade-summary"><div className="instrument-icon"><Layers3 size={25} /></div><div><h2>Simulated bond units <span>DEMOBOND / DEMOUSD</span></h2><p>{trade.id} · {trade.sources.buyer?.record.instrument_id ?? trade.sources.broker?.record.instrument_id} · <time dateTime={trade.sources.buyer?.record.settlement_date ?? trade.sources.broker?.record.settlement_date}>{trade.sources.buyer?.record.settlement_date ?? trade.sources.broker?.record.settlement_date}</time></p></div>{settled ? <span className="status-ready trade-status">Settled on Sui</span> : chain?.agreement_id ? <span className="status-ready trade-status">Committed on Sui</span> : <span className="status-warning">{!trade.sources.buyer || !trade.sources.broker ? 'Awaiting source record' : reconciliation.differences.length ? 'Intervention required' : 'Human verification required'}</span>}</section>
              <ol className="workflow" aria-label="Trade lifecycle"><li className={trade.sources.buyer && trade.sources.broker ? 'complete' : 'current'}>{trade.sources.buyer && trade.sources.broker ? <Check size={15} /> : <span className="step-number">1</span>}<span>Compare records</span></li><li className={latest ? 'complete' : 'current'}>{latest ? <Check size={15} /> : <span className="step-number">2</span>}<span>Propose terms</span></li><li className={approvalsDone ? 'complete' : latest ? 'current' : ''}>{approvalsDone ? <Check size={15} /> : <span className="step-number">3</span>}<span>Human approvals</span></li><li className={settled ? 'complete' : approvalsDone ? 'current' : ''}>{settled ? <Check size={15} /> : <span className="step-number">4</span>}<span>Commit & settle</span></li></ol>
              {latest && !settled && <p className="workflow-note">{session.hosted ? 'Steps 3 and 4 do not run in the hosted demo. Human approval needs World ID in the local app, and settlement needs Sui; see the README.' : chain?.agreement_id ? 'Committed on Sui. Each side funds only its own leg, then both legs settle in one transaction.' : trade.canonical ? (suiPackage ? `Both approvals staged version ${trade.canonical.version} as the correction. Commit it on Sui below.` : `Both approvals staged version ${trade.canonical.version} as the correction. Sui is not connected in this environment.`) : !world.approvals_ready ? 'Steps 3 and 4 stay blocked until World ID approvals are configured. See Connections.' : 'Each approver verifies with World ID, then approves or rejects this exact version.'}</p>}
              {reconciliation.differences.length > 0 && <section className={`mismatch-banner ${settled ? 'resolved' : ''}`}><span className="difference-symbol" aria-hidden="true">{settled ? '=' : '≠'}</span><div><strong>{reconciliation.differences.some(d => d.field === 'quantity') ? `${amount(reconciliation.differences.find(d => d.field === 'quantity')!.delta!.replace('-', ''))}-unit quantity difference` : 'Trade terms do not match'}</strong><p>{settled ? `Resolved by approved v${chain?.version} and settled atomically on Sui. Both original records are preserved.` : chain?.agreement_id ? `Approved v${chain.version} is committed on Sui. Settlement runs once both legs are funded.` : `${reconciliation.differences.length} fields differ between the books. Settlement stays blocked until the same corrected version is approved by both sides.`}</p></div><LockKeyhole size={19} /></section>}
              <div className="review-grid"><div className="evidence-column"><Evidence trade={trade} reconciliation={reconciliation} /><AgentReview trade={trade} side={session.principal.side} kind={session.principal.kind} configured={modelConfigured} hosted={Boolean(session.hosted)} onSaved={refresh} /><ApprovalCards version={latest?.version} trade={trade} session={session} world={world} attested={attested} approvals={reconciliation?.approvals} onSaved={refresh} />{chain && <ChainSettlement trade={trade} chain={chain} session={session} approvals={reconciliation?.approvals} onChanged={refresh} />}<section className="boundary-note"><ShieldCheck size={18} /><p>{settled ? <><strong>Settled on Sui.</strong> Both legs moved in one verified transaction; the original books are unchanged.</> : chain?.agreement_id ? <><strong>Agreement committed on Sui.</strong> Assets move only when both legs are funded and settlement succeeds atomically.</> : <><strong>Proposals are not payments.</strong> No correction has been applied, no agreement committed, and no assets moved.</>}</p></section></div><Proposal key={trade.tenant + trade.id} trade={trade} onSaved={refresh} /></div>
            </>}
          </section>
          {view === 'audit' && <section className="panel audit-panel"><header className="panel-heading"><div><h2>Activity for {tradeId}</h2><p>Server-confirmed events · UTC</p></div><FileClock size={20} /></header>{audit.length ? <ol className="audit-list">{[...audit].reverse().map(event => <li key={event.sequence}><span className="audit-dot"><Check size={14} /></span><div><h3>{event.action === 'SOURCE_IMPORTED' ? `${event.detail.side === 'buyer' ? 'Buyer' : 'Broker'} source imported` : event.action === 'CANDIDATE_PROPOSED' ? `Proposal v${event.detail.version} created` : event.action.replaceAll('_', ' ').toLowerCase()}</h3><p>{event.actor}</p>{event.detail.terms_hash && <Hash value={event.detail.terms_hash} />}</div><time dateTime={event.at}>{dateTime(event.at)}</time></li>)}</ol> : <Empty title="No saved events yet">Import a source record to begin the audit trail.</Empty>}</section>}
          {view === 'agreement' && <section className="panel"><header className="panel-heading"><div><h2>{latest ? `Candidate agreement v${latest.version}` : 'No candidate agreement yet'}</h2><p>The final agreement will be immutable once confirmed on Sui.</p></div><ShieldCheck size={22} /></header>{latest ? <section className="agreement-content">{chain?.agreement_id ? <Notice>Committed on Sui as an immutable agreement: <a href={chain.agreement_url ?? undefined} target="_blank" rel="noreferrer">{chain.agreement_id.slice(0, 10)}…</a></Notice> : <Notice>{trade?.canonical?.version === latest.version ? 'Both approvals recorded. This version is the staged correction; chain commitment is still required.' : 'Candidate only. Human approvals and chain commitment are still required.'}</Notice>}<dl className="terms-list"><div><dt>Quantity</dt><dd>{amount(latest.terms.quantity)} DEMOBOND</dd></div><div><dt>Unit price</dt><dd>{amount(latest.terms.unit_price_base, 2)} DEMOUSD</dd></div><div><dt>Net payment</dt><dd>{amount(latest.terms.net_cash_base, 2)} DEMOUSD</dd></div><div><dt>Expires</dt><dd>{dateTime(latest.terms.expires_at)}</dd></div></dl><h3>Terms commitment</h3><Hash value={latest.terms_hash} /><details><summary>Inspect all approval-bound fields</summary><pre>{JSON.stringify(latest.terms, null, 2)}</pre></details><ApprovalCards version={latest.version} trade={trade!} session={session} world={world} attested={attested} approvals={reconciliation?.approvals} onSaved={refresh} /></section> : <Empty title="Prepare the terms first">Create a correction from Trade review. Both original records will remain intact.</Empty>}</section>}
          {view === 'connections' && <Connections world={world} suiPackage={suiPackage} />}
        </>}
        <footer className="workspace-footer"><span>TradeBridge · Evidence before execution</span><span>Simulated assets. No real-world value.</span></footer>
      </main>
    </div>
  </div>;
}

function ApprovalCards({ version, trade, session, world, attested, approvals, onSaved }: { version?: number; trade: Trade; session: Session; world: WorldStatus; attested: boolean; approvals?: Record<string, string>; onSaved: () => Promise<void> }) {
  const why = (side: string) => !version ? 'Create a proposal first.'
    : session.hosted ? 'Not available in the hosted demo. World ID approval runs in the local app with a staging World ID app.'
    : !world.configured ? 'Connect a World ID app and verified staff identity to enable.'
    : session.principal?.kind !== 'human' ? `Agents cannot verify or approve. Sign in as the ${side} approver.`
    : session.principal.side !== side ? `Only the ${side} approver can verify here.`
    : !world.approvals_ready ? 'Proofs can verify, but approval stays blocked until staff enrollment and presence checks are connected.'
    : 'Verification is bound to this exact version and terms hash.';
  return <section className="approval-section"><header><h2>Two people. One agreement.</h2><span>{version ? `Version ${version}` : 'Awaiting proposal'}</span></header>{world.trust === 'demo_static_roster' && <p className="demo-trust"><strong>Demo trust boundary.</strong> Staff enrollment is a static roster of one buyer and one broker approver, World ID runs in {world.environment ?? 'staging'}, and presence is taken as IDKit reports it. This is not production staff authentication.</p>}<div className="approver-grid">{(['Buyer', 'Broker'] as const).map(side => {
    const status = approvals?.[side.toLowerCase()] ?? 'AWAITING_WORLD_ID';
    const recorded = ['HUMAN_APPROVED', 'CONSUMED', 'REJECTED'].includes(status);
    return <section key={side} className="approver"><div className="approver-title"><span className="approval-icon"><Fingerprint size={21} /></span><div><h3>{side} approver</h3><p>{status === 'AWAITING_WORLD_ID' ? 'Awaiting World ID' : status === 'HUMAN_APPROVED' ? 'Approved with World ID' : status === 'CONSUMED' ? (attested ? 'Approval attested on Sui' : 'Approved · correction staged') : status.replaceAll('_', ' ').toLowerCase()}</p></div><LockKeyhole size={16} /></div><div className="approval-state"><span><CircleDashed size={14} />Human verification</span><strong>{recorded ? 'Recorded' : 'Pending'}</strong></div><div className="approval-state"><span><CircleDashed size={14} />Explicit approval</span><strong>{status === 'REJECTED' ? 'Rejected' : recorded ? 'Recorded' : status === 'EXPIRED' ? 'Expired' : 'Pending'}</strong></div><Suspense fallback={<Button className="full" disabled>Loading World ID…</Button>}>{!recorded && world.configured && !session.hosted && session.principal?.kind === 'human' && session.principal.side === side.toLowerCase() ? <WorldVerification key={`${side}-${version}`} trade={trade} onSaved={onSaved} /> : <Button className="full" disabled><Fingerprint size={16} />{recorded ? 'Decision recorded' : 'Verify with World ID'}</Button>}</Suspense><small>{recorded ? 'Bound to this version and exact terms hash.' : why(side.toLowerCase())}</small></section>;
  })}</div></section>;
}
function Connections({ world, suiPackage }: { world: WorldStatus; suiPackage: string | null }) {
  return <section className="panel connections"><header className="panel-heading"><div><h2>Connected capabilities</h2><p>Local functionality and external integration readiness.</p></div><Link2 size={21} /></header>{[{ title: 'Reconciliation service', status: 'Available locally', text: 'CSV evidence, exact comparison, versioned proposals and persistent audit.', Icon: ArrowLeftRight, ready: true }, { title: 'World ID', status: world.trust === 'demo_static_roster' ? 'Demo trust boundary' : world.approvals_ready ? `Approvals enabled · ${world.environment}` : world.configured ? 'Trust checks pending' : 'App configuration required', ready: world.approvals_ready && world.trust !== 'demo_static_roster', text: world.trust === 'demo_static_roster' ? `Proof of Human with fresh presence, verified on the server against World's ${world.environment ?? 'staging'} environment. Demo only: a static roster stands in for staff enrollment, and presence is taken as IDKit reports it.` : world.approvals_ready ? 'Proof of Human with World App presence, verified on the server. Each approver binds to one verified person per version, and one person can never approve both sides. Staff checks use the development directory.' : 'Proof of Human with fresh presence. Staff authority and server-verified presence remain mandatory before consent is accepted.', Icon: Fingerprint }, { title: 'Sui settlement', status: suiPackage ? 'Live on testnet' : 'Not deployed', text: suiPackage ? `Package ${suiPackage.slice(0, 10)}… settles agreements, escrow funding and atomic delivery-versus-payment on Sui testnet with simulated assets.` : 'Move agreement and escrow contracts pass local scenario tests. No live agreement, funding or settlement is claimed.', Icon: Layers3, ready: Boolean(suiPackage) }].map(({ title, status, text, Icon, ready }) => <section key={title} className="connection-row"><span className="connection-icon"><Icon size={24} /></span><div><h3>{title}</h3><p>{text}</p></div><span className={ready ? 'status-ready' : 'status-neutral'}>{status}</span></section>)}<section className="connection-help"><h3>Integration boundaries</h3><p>World ID proves human participation; organizational authority and approval of the exact trade are separate checks. Without a trust adapter, approval stays blocked. The optional demo roster is staging-only and labelled wherever it is active.</p><a href="https://docs.world.org/world-id/idkit/integrate" target="_blank" rel="noreferrer">World ID setup documentation <ArrowRight size={15} /></a></section></section>;
}
function ImportSource({ tradeId, revision, side, onSaved }: { tradeId: string; revision: number; side: string; onSaved: () => Promise<void> }) {
  const [csv, setCsv] = useState(''); const [name, setName] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const intent = useRef<{ body: string; key: string } | null>(null);
  return <details className="import-source"><summary><Upload size={15} />Import {side} source CSV</summary><form noValidate onSubmit={async event => { event.preventDefault(); setError(''); if (!csv) { setError('Choose a CSV file before importing.'); return; } const body = { csv, expected_revisions: { [tradeId]: revision } }; const signature = JSON.stringify(body); if (intent.current?.body !== signature) intent.current = { body: signature, key: crypto.randomUUID() }; setBusy(true); try { await api('/imports', { method: 'POST', body, key: intent.current.key }); await onSaved(); setMessage(`${name} imported. Original evidence preserved.`); setCsv(''); intent.current = null; } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }}><label htmlFor="csv-file">One trade per file, using the documented TradeBridge CSV fields.</label><input id="csv-file" type="file" accept=".csv,text/csv" onChange={async event => { const file = event.target.files?.[0]; setMessage(''); if (!file) return; if (file.size > 500_000) { setError('Choose a CSV smaller than 500 KB.'); setCsv(''); return; } setName(file.name); setCsv(await file.text()); setError(''); }} /><Button type="submit" busy={busy}><ArrowDownToLine size={16} />Import source</Button>{error && <Notice error>{error}</Notice>}{message && <Notice>{message}</Notice>}</form></details>;
}
